cat echo a > out.txt
cat Headers/Assets.h >> out.txt
cat Headers/CSVHandler.h >> out.txt
cat Headers/FileHandler.h >> out.txt
cat CSVHandler.cpp >> out.txt
cat FileHandler.cpp >> out.txt
cat main.cpp >> out.txt
cat Headers/Matrix.h >> out.txt
cat Matrix.cpp >> out.txt
cat Headers/Portfolio.h >> out.txt
cat Headers/Window.h >> out.txt
cat Portfolio.cpp >> out.txt
cat Window.cpp >> out.txt
cat Headers/PortfolioOptimiser.h >> out.txt
cat Headers/ConjugateGradientOptimiser.h >> out.txt
cat ConjugateGradientOptimiser.cpp >> out.txt
cat Assets.cpp >> out.txt
cat PortfolioParameter.cpp >> out.txt
cat Headers/PortfolioParameter.h >> out.txt
cat Headers/TargetReturns.h >> out.txt
cat TargetReturns.cpp >> out.txt